# Generated by Django 6.0.4 on 2026-04-18 16:04

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='verification_token',
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_otp',
            field=models.CharField(default=accounts.models.generate_otp, editable=False, max_length=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_otp_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
