# Generated by Django 6.0.4 on 2026-05-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
