# Generated by Django 5.2.5 on 2025-09-18 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='time',
            new_name='created_at',
        ),
    ]
